[package]
name = "sudoku-solver"
version = "0.1.0"
authors = ["Aaron Ti <https://github.com/mcdulltii>"]

[dependencies]
piston = "0.50.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.64.0"
piston2d-opengl_graphics = "0.72.0"
find_folder = "0.3.0"
piston_window = "0.109.0"
